language: ruby
addons:
  apt:
    packages:
    - build-essential
    - bzr
    - dh-make
    - bzr-builddeb
rvm:
- 2.3.3
#env:
#  global:
#  - NO_EXCLUDE=yes
#  matrix:
#  - RUBYVER=check
script:
- make bootstrap
- make p
#after_script:
#- scripts/submit.sh
branches:
  only:
    - master
