language: ruby
addons:
  apt:
    packages:
    - build-essential
    - software-properties-common
    - bzr
    - dh-make
    - bzr-builddeb
rvm:
- 2.4.0
#env:
#  global:
#  - NO_EXCLUDE=yes
#  matrix:
#  - RUBYVER=check
script:
- ruby -v
- make bootstrap
- make p
#after_script:
#- scripts/submit.sh
branches:
  only:
    - master
