dist: trusty
sudo: required
language: c
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
    - build-essential
    - software-properties-common
    - bzr
    - dh-make
    - bzr-builddeb
env:
  global:
  - RUBY_PKG_VERSION=2.4.0
#  matrix:
#  - RUBYVER=check
script:
- ruby -v
- which ruby
- /usr/bin/ruby -v
- make bootstrap
- make p
#after_script:
#- scripts/submit.sh
branches:
  only:
    - master
