dist: trusty
sudo: required
language: c
os:
  - linux
compiler:
  - gcc
addons:
  apt:
    packages:
    - build-essential
    - software-properties-common
    - bzr
    - dh-make
    - bzr-builddeb
before_install:
- ssh-agent > ~/.ssh/agent_env
- openssl aes-256-cbc -K $encrypted_4e3668ecae45_key -iv $encrypted_4e3668ecae45_iv -in etc/deploy.enc -out etc/deploy -d
- chmod 600 etc/deploy
- git config --global user.email "wojciech@koszek.com"
- git config --global user.name "Wojciech A. Koszek"
env:
  global:
  - RUBY_PKG_VERSION=2.4.1
#  matrix:
#  - RUBYVER=check
script:
- ruby -v
- which ruby
- /usr/bin/ruby -v
- make bootstrap
- make p
branches:
  only:
    - master
